### ISSUE TITLE
Pytorch is installed but does not run on Windows.

### ISSUE THREAD

**Issue by dev-0911** [angry-dev-2187/pytorch#2]
import torch
Traceback (most recent call last):
File “”, line 1, in
File “C:\Users\pc\ali\Lib\site-packages\torch_init_.py”, line 141, in
raise err
OSError: [WinError 126] The specified module could not be found. Error loading “C:\Users\pc\ali\Lib\site-packages\torch\lib\fbgemm.dll” or one of its dependencies.

**Comment by angry-dev-2187** [comment]
import torch
Traceback (most recent call last):
File “”, line 1, in
File “C:\Users\pc\ali\Lib\site-packages\torch_init_.py”, line 141, in
raise err
OSError: [WinError 126] The specified module could not be found. Error loading “C:\Users\pc\ali\Lib\site-packages\torch\lib\fbgemm.dll” or one of its dependencies.

**Comment by angry-dev-2187** [comment]
This problem is solved.
https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969

**Comment by dev-0911** [comment]
This problem is solved.
https://discuss.pytorch.org/t/failed-to-import-pytorch-fbgemm-dll-or-one-of-its-dependencies-is-missing/201969
